from pathlib import Path
import re
p=Path('index.html')
s=p.read_text()

history="""function rewardTier(v){v=Number(v||0);if(v===888)return'tier-jackpot';if(v>=200)return'tier-gold';if(v>=120)return'tier-green';if(v>=100)return'tier-red';return'tier-blue'}
async function loadHistory(){if(!session)return;$('refreshHistoryBtn').disabled=true;$('refreshHistoryBtn').textContent='查询中…';$('historyList').innerHTML='<div class=\"empty\">正在读取抽奖记录…</div>';const d=await rpc('member_session_draw_history',{p_token:session.token,p_limit:50});$('refreshHistoryBtn').disabled=false;$('refreshHistoryBtn').textContent='刷新';if(!d.ok){$('historyList').innerHTML='<div class=\"empty\">'+esc(d.message||'查询失败')+'</div>';return}const rows=Array.isArray(d.records)?d.records:[];if(!rows.length){$('historyList').innerHTML='<div class=\"empty\">暂时还没有抽奖记录</div>';return}$('historyList').innerHTML=rows.map(r=>{const reward=Number(r.reward||0),temporary=r.draw_type==='temporary'||!!r.lucky_code,type=temporary?'幸运码':'惊喜盲盒',cls=temporary?'tempType':'normalType',extra=temporary&&r.lucky_code?' · '+esc(r.lucky_code):'',badge=reward===888?'<span class=\"recordBadge\">至尊大奖</span>':reward>=200?'<span class=\"recordBadge\">好运高光</span>':'';return '<div class=\"record '+rewardTier(reward)+'\"><div class=\"recordTop\"><span class=\"time\">'+formatDate(r.drawn_at)+'</span><span class=\"type '+cls+'\">'+type+extra+'</span>'+badge+'</div><div class=\"amt\">¥'+reward+'</div><div class=\"serial\">'+esc(r.serial||'')+'</div></div>'}).join('')}
"""
s,n=re.subn(r"async function loadHistory\(\)\{.*?\}\nfunction formatDate",history+'function formatDate',s,count=1,flags=re.S)
if n!=1: raise SystemExit('history patch failed')

recovery="""async function recoverPendingDraw(silent=false,attempts=3){const p=getPending();if(!p||!session)return false;if(p.memberCode!==session.code){clearPending();return false}drawing=true;$('stage').classList.remove('explode');$('stage').classList.add('opening');$('stageText').innerHTML='好运正在确认…<small>这一次的惊喜正在为你找回</small>';let d;for(let i=0;i<attempts;i++){d=p.kind==='lucky'?await rpc('member_session_lucky_draw_safe',{p_token:session.token,p_request_id:p.requestId,p_lucky_code:p.luckyCode}):await rpc('member_session_draw_safe',{p_token:session.token,p_request_id:p.requestId});if(d.ok||!d.network_error)break;await wait(650*(i+1))}if(d&&d.ok){clearPending();switchTab('home');await runCardSequence(d.reward);await explodeChest(d.reward);openResult(d,p.kind==='lucky'?'temp':'normal');drawing=false;loadSummary();return true}drawing=false;$('stage').classList.remove('opening');clearCards();updateStageText();if(d&&!d.network_error){clearPending();if(String(d.message||'').includes('登录状态'))logoutMember();else if(!silent)showNotice(d.message||'开奖未完成，请稍后再试','开奖提示','🎁')}else if(!silent)showNotice('网络有些波动，但这次开奖编号已经安全保存。\n恢复网络后重新打开页面，系统会自动确认原来的结果，不会重复扣次数。','结果正在守候','🛡️');return false}
"""
marker='async function drawFromChest(){'
if marker not in s: raise SystemExit('draw marker missing')
s=s.replace(marker,recovery+marker,1)

draw="""async function drawFromChest(){if(!session){openLoginModal('home','登录后就能开启这个惊喜宝箱');return}if(drawing)return;if(session.credits<=0){showNotice('当前暂无可用抽奖次数，获得新的抽奖机会后再来开启吧。','惊喜盲盒','🎁');return}if(getPending()){await recoverPendingDraw(false,3);return}initAudio();playStartSound();drawing=true;$('stage').classList.remove('explode');$('stage').classList.add('opening');clearCards();const id=newRequestId();savePending('normal',id);const request=rpc('member_session_draw_safe',{p_token:session.token,p_request_id:id});let idx=lastCardIndex<0?0:(lastCardIndex+1)%8,cards=[...document.querySelectorAll('.prize')];$('stageText').innerHTML='好运启动…<small>今天的幸运正在靠近</small>';for(let i=0;i<10;i++){lightCard(idx,false,'fast');idx=(idx+1)%cards.length;await wait(62+i*3)}const d=await request;if(!d.ok){drawing=false;if(d.network_error){await recoverPendingDraw(false,3);return}clearPending();$('stage').classList.remove('opening');clearCards();updateStageText();if(String(d.message||'').includes('登录状态'))logoutMember();else showNotice(d.message||'开奖未完成，请稍后再试','开奖提示','🎁');return}clearPending();lastCardIndex=(idx-1+cards.length)%cards.length;await runCardSequence(d.reward);await explodeChest(d.reward);openResult(d,'normal');drawing=false;loadSummary()}
"""
s,n=re.subn(r"async function drawFromChest\(\)\{.*?\}\nasync function drawAgain",draw+'async function drawAgain',s,count=1,flags=re.S)
if n!=1: raise SystemExit('draw patch failed')

lucky="""async function tempDraw(){if(!session){openLoginModal('lucky');return}const luck=$('luckyCode').value.trim();if(!luck){showNotice('请输入幸运码后再开启专享惊喜。','幸运码','🎟️');return}if(getPending()){await recoverPendingDraw(false,3);return}initAudio();playStartSound();const id=newRequestId();savePending('lucky',id,luck);$('tempDrawBtn').disabled=true;$('tempDrawBtn').textContent='正在开奖…';const d=await rpc('member_session_lucky_draw_safe',{p_token:session.token,p_request_id:id,p_lucky_code:luck});$('tempDrawBtn').disabled=false;$('tempDrawBtn').textContent='使用幸运码抽奖';if(!d.ok){if(d.network_error){await recoverPendingDraw(false,3);return}clearPending();if(String(d.message||'').includes('登录状态'))logoutMember();else showNotice(d.message||'幸运码暂时无法使用','幸运码提示','🎟️');return}clearPending();switchTab('home');$('stage').classList.add('opening');clearCards();await runCardSequence(d.reward);await explodeChest(d.reward);openResult(d,'temp');loadSummary()}
"""
s,n=re.subn(r"async function tempDraw\(\)\{.*?\}\nrenderSession\(\);restoreSession\(\);",lucky+'renderSession();restoreSession();',s,count=1,flags=re.S)
if n!=1: raise SystemExit('lucky patch failed')
p.write_text(s)
